== Annotations

=== @OnClick

This annotation will trigger an event when a View (for example, a Button) is clicked.

==== How to use

The method should be this way:

[source, groovy]
----
public void onClick()
public void onClick(View v)
----

==== Example

[source, groovy]
----
@OnClick(R.id.button)
public void onClick() {
    Toast.makeText(this, "Button clicked", Toast.LENGTH_SHORT).show();
}
----

=== @OnLongClick

This annotation will trigger an event when a View (for example, a Button) is long-clicked.

==== How to use

The method should be this way:

public boolean onLongClick()
public boolean onLongClick(View v)
Notice it must return a boolean

==== Example

[source, groovy]
----
@OnLongClick(R.id.button)
public boolean onLongClick() {
    Toast.makeText(this, "Button long clicked", Toast.LENGTH_SHORT).show();
    return true;
}
----

TIP: More information about return http://developer.android.com/reference/android/view/View.OnLongClickListener.html[View.OnLongClickListener]

=== @OnItemClick

This annotation will trigger an event when an AbsListView (ListView, GridView...) item is clicked.

==== How to use

The method should be this way (the method and variable names can be changed):

[source, groovy]
----
public void onItemClick(int position)
public void onItemClick(int position, AdapterView adapterView)
public void onItemClick(int position, AdapterView adapterView, View clickedView)
----

==== Example

[source, groovy]
----
@OnItemClick(R.id.list)
public void onItemClick(int position) {
    Toast.makeText(this, "Item $position clicked", Toast.LENGTH_SHORT).show();
}
----

=== @OnItemLongClick

This annotation will trigger an event when an AbsListView (ListView, GridView...) item is long-clicked.

==== How to use

The method should be this way (the method and variable names can be changed):

[source, groovy]
----
public boolean onItemClick(int position)
public boolean onItemClick(int position, AdapterView adapterView)
public boolean onItemClick(int position, AdapterView adapterView, View clickedView)
----

Notice it must return a boolean

==== Example

[source, groovy]
----
@OnItemLongClick(R.id.list)
public void onItemLongClick(int position) {
    Toast.makeText(this, "Item $position long-clicked", Toast.LENGTH_SHORT).show();
}
----

TIP: More information about return http://developer.android.com/reference/android/view/View.OnLongClickListener.html[View.OnItemLongClick]

=== @OnItemSelected

This annotation will trigger an event when an AbsListView (ListView, GridView...) item is selected.

==== Annotation arguments

@OnItemSelected uses an extra "method" argument to specify the listener method which will call this method.

The annotation must be:

[source, groovy]
----
@OnItemSelected(value=R.id.my_view, method=OnItemSelected.Method.ITEM_SELECTED)
// or
@OnItemSelected(value=R.id.my_view, method=OnItemSelected.Method.NOTHING_SELECTED)
----

==== How to use

The method should be this way (the method and variable names can be changed):

[source, groovy]
----
public void onItemSelected(int position)
public void onItemSelected(int position, AdapterView adapterView)
public void onItemSelected(int position, AdapterView adapterView, View clickedView)

public void onNothingSelected(AdapterView adapterView)
----

==== Example

[source, groovy]
----
@OnItemSelected(value=R.id.list, method=OnItemSelected.Method.ITEM_SELECTED)
public void onItemSelected(int position) {
    Toast.makeText(this, "Item $position selected", Toast.LENGTH_SHORT).show();
}
----

=== @OnChecked

This annotation will trigger an event when a CompoundButton (for example, a RadioButton) is checked.

==== How to use

The method should be this way:

[source, groovy]
----
public boolean onChecked(boolean checked)
public boolean onChecked(CompoundButton button, boolean checked)
----

==== Example

[source, groovy]
----
@OnChecked(R.id.radio_button)
public public boolean onChecked(CompoundButton button, boolean checked) {
    Toast.makeText(this, "Button checked: $checked", Toast.LENGTH_SHORT).show();
    return false;
}
----

=== @OnFocusChanged

This annotation will trigger an event when a View receives or loses focus.

==== How to use

The method should be this way:

[source, groovy]
----
public void onFocusChanged(boolean hasFocus)
public void onFocusChanged(View v, boolean hasFocus)
----

==== Example

[source, groovy]
----
@OnFocusChanged(R.id.my_view)
public void onFocusChanged(boolean hasFocus) {
    Toast.makeText(this, "View has focus: $hasFocus", Toast.LENGTH_SHORT).show();
}
----

=== @OnTouch

This annotation will trigger an event when a View is touched.

==== How to use

The method should be this way:

[source, groovy]
----
public boolean onTouch(MotionEvent event)
public boolean onClick(View v, MotionEvent event)
----

==== Example

[source, groovy]
----
@OnTouch(R.id.button)
public boolean onTouch(MotionEvent event) {
    Toast.makeText(this, "Button touched, action: $event.action", Toast.LENGTH_SHORT).show();
    return false;
}
----

=== @OnPageChanged

This annotation will trigger an event when a ViewPager scroll changes.

==== Annotation arguments

@OnPageChanged uses an extra "method" argument to specify the listener method which will call this method.

The annotation must be:

[source,groovy]
----
@OnPageChanged(value=R.id.view_pager, method=OnPageChanged.Method.PAGE_SCROLLED)
// or
@OnPageChanged(value=R.id.view_pager, method=OnPageChanged.Method.PAGE_SELECTED)
// or
@OnPageChanged(value=R.id.view_pager, method=OnPageChanged.Method.PAGE_SCROLL_STATE_CHANGED)
----

==== How to use

The method should be this way (the method and variable names can be changed):

[source, groovy]
----
public void onPageScrolled(int position)
public void onPageScrolled(int position, float offset, int pixelOffset)

public void onPageSelected(int position)

public void onPageScrollStateChanged(int state)
----

==== Example

[source, groovy]
----
@OnPageChanged(value=R.id.list, method=OnPageChanged.Method.PAGE_SELECTED)
public void onPageSelected(int position) {
    Toast.makeText(this, "Current page: $position", Toast.LENGTH_SHORT).show();
}
----

=== @OnTextChanged

This annotation will trigger an event when an EditText's text is changed.

==== Annotation arguments

@OnTextChanged uses an extra "method" argument to specify the listener method which will call this method.

The annotation must be:

[source, groovy]
----
@OnTextChanged(value=R.id.edit_text, method=OnTextChanged.Method.BEFORE_TEXT_CHANGED)
// or
@OnTextChanged(value=R.id.edit_text, method=OnTextChanged.Method.ON_TEXT_CHANGED)
// or
@OnTextChanged(value=R.id.edit_text, method=OnTextChanged.Method.AFTER_TEXT_CHANGED)
----

==== How to use

The method should be this way (the method and variable names can be changed):

**BeforeTextChanged**

[source, groovy]
----
public void beforeTextChanged(CharSequence sequence)
public void beforeTextChanged(TextView textView, CharSequence sequence)
public void beforeTextChanged(CharSequence sequence, int start, int count, int after)
public void beforeTextChanged(TextView textView, CharSequence sequence, int start, int count, int after)
----

**OnTextChanged**

[source, groovy]
----
public void onTextChanged(CharSequence sequence)
public void onTextChanged(TextView textView, CharSequence sequence)
public void onTextChanged(CharSequence sequence, int start, int before, int count)
public void onTextChanged(TextView textView, CharSequence sequence, int start, int before, int count)
----

**AfterTextChanged**

[source, groovy]
----
public void afterTextChanged(Editable editable)
----

==== Example

[source, groovy]
----
@OnTextChanged(value=R.id.edit_text, method=OnTextChanged.Method.ON_TEXT_CHANGED)
public void onTextChanged(CharSequence sequence) {
    Toast.makeText(this, "Sentence written: $sequence", Toast.LENGTH_SHORT).show();
}
----

=== @OnEditorAction

This annotation will trigger an event when a TextView receives an action such as pressing ENTER key or a custom action on the keyboard.

==== How to use

The method should be this way:

[source, groovy]
----
public boolean onEditorAction(KeyEvent event)
public boolean onEditorAction(TextView textView, KeyEvent event)
----

==== Example

[source, groovy]
----
@OnEditorAction(R.id.edit_text)
public boolean onEditorAction(KeyEvent event) {
    Toast.makeText(this, "Editor action received", Toast.LENGTH_SHORT).show();
    return false;
}
----

TIP: More information http://developer.android.com/reference/android/widget/TextView.html#setOnEditorActionListener(android.widget.TextView.OnEditorActionListener)[TextView.setOnEditorActionListener]

=== @OnUIThread

This annotation will execute the code inside the method on the UI Thread using a Handler.

==== Example

[source, groovy]
----
@OnUIThread()
public void getResult(Context context, boolean value){
    if(value == true) {
        Toast.makeText(context, "Result was: $value", Toast.LENGTH_SHORT).show()
    }
}
----

=== @OnBackground

This annotation will execute the code inside the method on a background Thread.

==== Example

[source, groovy]
----
@OnBackground()
public boolean getResult(){...}
----

=== @SaveInstance

This annotation will help you to reduce your persistance code. It has two sepparated behaviours: When it's applied to Views, and when it's not.

Instead of having to override the onSaveInstanceState method, add everything to the Bundle, check if the savedInstanceState was null at the onCreate... you can simplify it by only annotating a variable with @SaveState.

==== How to use

In order to work propperly, you must ensure that:

Your variable can be written to a Bundle object (check Bundle documentation)
You must make a call to SwissKnife.restoreState(this, savedInstanceState) in order for the state to be restored.

IMPORTANT: Keep calm. Don't worry if you manually override the onSaveInstanceState method with some code, it doesn't matter, SwissKnife will append any necessary statements to the already existing code

==== Example

[source, groovy]
----
@SaveInstance
public int myInt

// You can also set a custom tag to your variable
@SaveInstance("MYSTRING")
public String myString

@Override
public void onCreate(Bundle savedInstanceState){
    // Your previous code
    SwissKnife.restoreState(this, savedInstanceState)
}
----

In case your variable is not one of the types that can be written to a Bundle, the compilation will fail and show which class is giving the error.

Of course, it supports Parcelable objects (also arrays and ArrayLists).

Make sure you check the sample for more examples.

==== Views

@SaveInstance can also be used to save the state of views. Though Android usually will do that automatically if the view has an id, you can still use this annotation to force that restoration or use it on views without id.

[source, groovy]
----
@SaveInstance
TextView myTextView;

@Override
public void onCreate(Bundle savedInstanceState){
    // Your previous code
    if(savedInstanceState == null) {
         // If the Activity recreates, myTextView will retain the "Hey!" text
         myTextView.setText("Hey!")
    }
    SwissKnife.restoreState(this, savedInstanceState)
}
----

How is this done? Every view has two methods, onSaveInstanceState() and onRestoreInstanceState(Parcelable) in which they will store their state when called. Usually those methods are called from their containing Activities and Fragments as they are destroyed and recreated when their homonymous methods are called. SwissKnife just forces those calls when needed.

=== @Parcelable

`@Parcelable` lets you automatically turn any class into a Parcelable object.

It will pick every parcelable or serializable attribute of the annotated class and put it into a `Parcel` object, just like you would have to do implementing the Parcelable interface.
[source, groovy]
----
public void writeToParcel(Parcel parcel, int flags)

public int describeContents()

public static Parcelable.Creator CREATOR

// Constructor to create a MyClass instance from a Parcel object
public MyClass(Parcel source)
----

Also, it will create a `MyClass.Creator` class which will implement `Parcelable.Creator` for you.

==== How to use

Just add `@Parcelable` annotation to the class you want to use as a Parcelable object.

TIP: **What about circular dependencies?** Even having only a few classes, you can end up having circular dependencies, where having two parcelable classes A and B, A contains a B instance and B contains an A instance. If you used @Parcelable with them both your app would go crazy while trying to save them as it will end on a never-ending cycle. What to do here? Use exclude parameter on the annotation.

==== Exclude some properties

If there is some attribute that you don't want parceled, you can explicitly do that using the `exclude` parameter on the annotation like this:

[source, groovy]
----
@Parcelable(exclude={anotherObject;andThisToo})
class ParcelableClass {
...
    ParcelableClass anotherObject
    SomeOtherClass andThisToo
----

==== Example

[source, groovy]
----
@Parcelable
class ParcelableClass {

    int id
    String name

}
----

Will generate:

[source, groovy]
----
class ParcelableClass implements Parcelable {
...
    public ParcelableClass(Parcel source) {
        this.id = source.readInt()
        this.name = source.readString()
    }

    public void writeToParcel(Parcel out) {
        out.writeInt(id)
        out.writeString(name)
   }
...
----

What classes can be parceled?

As previously said, `@Parcelable` will only parcel what can be put into a Parcel object. This classes are:

* String
* String[]
* List
* Map
* SparseArray
* Parcelable
* Parcelable[]
* Bundle
* CharSequence
* Serializable

Of course, **any other primitive variable (int, long, float, char, etc.) can be parceled too** , as well as arrays (int[], double[]...).

Also, please take in mind that `static` variables won't be parceled as they don't belong to a single instance.

=== @Extra

This annotation will generate hidden code for automatically parsing
Intent extras.

==== How to use

You would put extras on an _Intent_ as you usually do:

[source,groovy]
----
Intent goToActivityIntent = new Intent(this, SomeActivity.class)
goToActivityIntent.putExtra("some_key", "my api key")
startActivity(goToActivityIntent)
----

To parse the `"some_key"` extra, you would add this field:

[source,groovy]
----
@Extra("some_key")
String myKey

// or

@Extra
String some_key
----

And then, to load them, you would need to call:

[source, groovy]
----

public void onCreate(Bundle savedInstanceState) {
    ...
    SwissKnife.loadExtras(this)
    println myKey // It's usable!
}
----

==== What can be retrieved as an extra?

Almost everything that can be put into a Bundle, just like with `@SaveInstance`:

* Primitive types *(int, double, long, char...)*.
* Classes that implement `Parcelable` or `Serializable`.
* Arrays an Lists all above.
